"""Render a drafted PMFBY claim into a clean, print-ready PDF.

Uses fpdf2 with HarfBuzz text shaping + an embedded Noto Sans Devanagari font
so Marathi/Hindi render correctly (conjuncts and matras placed properly, no
tofu boxes). Latin tokens (PMFBY, NDVI, ₹, dates) render in the same font.
"""
from datetime import date
from pathlib import Path

from fpdf import FPDF

from .common import PROJECT_ROOT

FONT_DIR = PROJECT_ROOT / "assets" / "fonts"
FONT_REGULAR = FONT_DIR / "NotoSans-Regular.ttf"
FONT_BOLD = FONT_DIR / "NotoSans-Bold.ttf"
PDF_DIR = PROJECT_ROOT / "data" / "claims"

GREEN = (27, 94, 32)
GRAY = (110, 110, 110)
RED = (183, 28, 28)


class ClaimPDF(FPDF):
    def header(self) -> None:
        self.set_font("Noto", "B", 15)
        self.set_text_color(*GREEN)
        self.cell(0, 10, "PMFBY Crop Insurance Claim", new_x="LMARGIN", new_y="NEXT",
                  align="C")
        self.set_font("Noto", "", 13)
        self.cell(0, 8, "पीक विमा दावा अर्ज", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_draw_color(*GREEN)
        self.set_line_width(0.6)
        self.line(self.l_margin, self.get_y() + 1, self.w - self.r_margin, self.get_y() + 1)
        self.ln(6)

    def footer(self) -> None:
        self.set_y(-16)
        self.set_font("Noto", "", 8)
        self.set_text_color(*GRAY)
        self.cell(0, 5,
                  "System-generated by KisaanRaksha — प्रणालीद्वारे तयार केलेले. "
                  "Verify at your Taluka Krishi office.",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.cell(0, 5, f"Page {self.page_no()}", align="C")


def render_claim_pdf(claim_text: str, evidence: dict, out_path: Path | None = None,
                     simulation: bool = False) -> Path:
    """Render claim_text to a PDF file and return its path.

    evidence: the dict from draft_pmfby_claim (farmer_name, district_mr, crop,
    date, rain_deficit_pct, market_price_rs_qtl, msp_rs_qtl, ndvi, ...).
    """
    pdf = ClaimPDF(orientation="P", unit="mm", format="A4")
    pdf.add_font("Noto", "", str(FONT_REGULAR))
    pdf.add_font("Noto", "B", str(FONT_BOLD))
    pdf.set_text_shaping(True)  # HarfBuzz shaping for correct Devanagari
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(20, 18, 20)
    pdf.add_page()

    if simulation:
        pdf.set_font("Noto", "B", 10)
        pdf.set_text_color(*RED)
        pdf.cell(0, 7, "[SIMULATION — demo data, not a live claim]",
                 new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(2)

    # evidence summary box
    pdf.set_fill_color(232, 245, 233)
    pdf.set_draw_color(165, 214, 167)
    pdf.set_text_color(20, 40, 25)
    pdf.set_font("Noto", "B", 10)
    pdf.cell(0, 7, "Claim details / दाव्याचा तपशील", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Noto", "", 10)
    rows = [
        ("Farmer / शेतकरी", str(evidence.get("farmer_name", "____"))),
        ("District / जिल्हा", str(evidence.get("district_mr") or evidence.get("district", ""))),
        ("Crop / पीक", str(evidence.get("crop", ""))),
        ("Date / दिनांक", str(evidence.get("date", date.today().strftime("%d/%m/%Y")))),
    ]
    dfc = evidence.get("rain_deficit_pct")
    if dfc is not None:
        rows.append(("Rainfall deficit / पर्जन्य तूट", f"{dfc}%"))
    mp, msp = evidence.get("market_price_rs_qtl"), evidence.get("msp_rs_qtl")
    if mp and msp:
        rows.append(("Market price vs MSP", f"Rs.{mp}/qtl  vs  MSP Rs.{msp}/qtl"))
    if evidence.get("ndvi") is not None:
        rows.append(("Satellite NDVI", str(evidence.get("ndvi"))))
    for label, val in rows:
        pdf.cell(60, 6, label, border=0)
        pdf.set_font("Noto", "B", 10)
        pdf.multi_cell(0, 6, val, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Noto", "", 10)
    pdf.ln(4)

    # the drafted letter body
    pdf.set_text_color(15, 15, 15)
    pdf.set_font("Noto", "", 11)
    for para in claim_text.split("\n"):
        if para.strip():
            pdf.multi_cell(0, 6.6, para.strip(), new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.ln(3)

    out_path = out_path or (PDF_DIR / f"claim_{date.today().isoformat()}.pdf")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out_path))
    return out_path


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(PROJECT_ROOT))
    from mcp_server.tools.claim_draft import draft_pmfby_claim
    from mcp_server.tools.fsi import compute_fsi
    fsi = compute_fsi("Amravati", "cotton", simulate_crisis=True)
    claim = draft_pmfby_claim("रमेश पाटील", "Amravati", "cotton", fsi)
    p = render_claim_pdf(claim["claim_letter_marathi"], claim["evidence"],
                         PDF_DIR / "sample_claim.pdf", simulation=True)
    print("wrote", p)
